<<<<<<< HEAD
import type { Metadata } from 'next'
import './globals.css'
import SessionProvider from '@/components/SessionProvider'
import Sidebar from '@/components/Sidebar'
import NotificationBell from '@/components/NotificationBell'

export const metadata: Metadata = {
  title: 'Ateliê Sistema',
  description: 'Sistema de Produção',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <SessionProvider>
          <div className="flex min-h-screen bg-gray-50">
            <Sidebar />
            <div className="flex-1 flex flex-col min-w-0">
              {/* TOPO */}
              <header className="h-14 bg-white border-b border-gray-100 flex items-center justify-end px-4 md:px-8 gap-3 flex-shrink-0">
                {/* Espaço para o hamburguer no mobile */}
                <div className="flex-1 md:hidden" />
                <NotificationBell />
              </header>
              {/* CONTEÚDO */}
              <main className="flex-1 p-4 md:p-8 overflow-x-hidden">
                {children}
              </main>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  )
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
>>>>>>> 207ad57b321dc370732151e2e34243648c175230
}
